FlashCard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from CardGroups import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.url')),
    path('', include('CardGroups.url')),
    path('cards/', include('Cards.url')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

CardGroups/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.urls import reverse



class CardGroup(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='card_groups')
    name = models.CharField(max_length=50)
    study_duration =models.DurationField(null=True, blank=True)
    last_study_at =  models.DateTimeField(_('last study'), blank=True, null=True)
    study_count = models.IntegerField(default=0)

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('cardgroups:group_details', args=[self.pk])



    class Meta:
        db_table = "cardgroup"
        ordering = ["-study_count", 'id']

Cards/models.py
from CardGroups.models import CardGroup
from django.db import models


class Card(models.Model):
    card_group = models.ForeignKey(CardGroup, on_delete=models.CASCADE, related_name='cards')
    front = models.TextField()
    back = models.TextField()

    def __str__(self):
        return self.front


    class Meta:
        db_table = "card"
        ordering = ["-id"]

CardGroups/forms.py
from users.models import User
from CardGroups.models import CardGroup
from django import forms
import datetime
from django.core.exceptions import ValidationError


class DurationFieldCustom(forms.DurationField):

    def prepare_value(self, value):
        # đầu ra là số phút không phải kiểu mặc định của timedelta('00:10:00')
        if isinstance(value, datetime.timedelta):
            value = value.seconds // 60
        return value


    def to_python(self, value):
        # đầu vào là số phút
        try:
            study_duration_minute = int(value)
        except (ValueError, TypeError):
            return super().to_python(value)
        if study_duration_minute <= 0:
            raise ValidationError('Phải nhập số nguyên dương(đơn vị phút)', code='invalid')
        value = datetime.timedelta(seconds=study_duration_minute * 60)
        return super().to_python(value)



class CardGroupForm(forms.ModelForm, DurationFieldCustom):

    user = forms.ModelChoiceField(User.objects.all(), required=False, disabled=True)
    study_duration = DurationFieldCustom(
        error_messages={'invalid':'Phải nhập số nguyên dương(đơn vị phút)'},
        widget=forms.NumberInput(
            attrs={'class': 'form-control bg-input-group'}
        )
    )
    class Meta:
        model = CardGroup
        exclude = ['last_study_at', 'study_count']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control bg-input-group'
            })
        }

CardGroups/views.py
from datetime import datetime, timedelta
import random
from django.shortcuts import get_list_or_404, get_object_or_404, redirect, render
from django.views import generic
from django.contrib.auth.decorators import login_required
from CardGroups.models import CardGroup
from Cards.models import Card
from django.utils.decorators import method_decorator
from django.db.models import Count
from CardGroups.forms import CardGroupForm
from django.urls import reverse_lazy, reverse
from django.core.paginator import Paginator
from Cards.forms import CardForm
from django.utils import timezone
from django.forms.models import model_to_dict
from django.http import JsonResponse
from dateutil import parser
from django.contrib import messages
from django.db.models import F
from django.template import loader




@method_decorator(login_required, name='dispatch')
class CardGroupView(generic.ListView):
    model = CardGroup
    template_name = 'cardgroups/dashboard.html'

    def get_queryset(self):
        queryset = CardGroup.objects.prefetch_related('cards').annotate(
            card_count=Count('cards__id')
        ).filter(user_id=self.request.user.pk)

        if self.request.GET.get('group'):
            queryset = queryset.filter(name__icontains=self.request.GET.get('group'))
        return queryset



@method_decorator(login_required, name='dispatch')
class CreateGroup(generic.CreateView):
    model = CardGroup
    form_class = CardGroupForm
    template_name = 'cardgroups/create_group.html'


    def get_success_url(self):
        return reverse('cards:create_card', args=[self.object.pk, 'begin'])


    def get_initial(self):
        init = super().get_initial()
        init['user'] = self.request.user.pk
        return init




@method_decorator(login_required, name='dispatch')
class DeleteGroup(generic.DeleteView):
    model = CardGroup
    success_url = reverse_lazy('cardgroups:learn')



@method_decorator(login_required, name='dispatch')
class UpdateGroup(generic.UpdateView):
    model = CardGroup
    form_class = CardGroupForm
    template_name = 'cardgroups/group_details.html'


    def get_cards(self):
        cards = self.group.cards.all()
        return cards


    def get_card_paginator(self, limit):

        return Paginator(self.get_cards(), limit)


    def get_card_page(self):
        try:
            limit = self.request.GET['limit']
        except KeyError:
            limit = 5
        card_paginator = self.get_card_paginator(limit)
        if self.request.GET.get('page'):
            try:
                page_number = int(self.request.GET.get('page'))
            except ValueError:
                return card_paginator.get_page(1)

            if page_number >=1 and page_number <= card_paginator.num_pages:
                return card_paginator.get_page(page_number)
        return card_paginator.get_page(1)


    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        queryset = CardGroup.objects.prefetch_related('cards').annotate(
            card_count=Count('cards__id')
        )
        self.group = get_object_or_404(queryset, user_id=self.request.user.pk, id=self.kwargs['pk'])
        context_data['cardgroup'] = self.group
        context_data['cards_page'] = self.get_card_page()
        cards = context_data['cards_page'].object_list
        context_data['cards_forms'] = [CardForm(instance=card) for card in cards]
        return context_data




@login_required()
def StudyView(request, pk):
    card_group = get_object_or_404(CardGroup, pk=pk, user=request.user)
    
    expire_date = set_expire_date(request, card_group)
    cards = Card.objects.filter(card_group_id=pk, card_group__user=request.user)
    study_type = set_study_type(request, pk)
    if not cards.exists():
        messages.error(request, 'Không có card để học. Vui lòng thêm card')
        return redirect(reverse('cardgroups:group_details', args=[pk]))

    if request.method == 'GET':
        expire_date = set_expire_date(request, card_group)
    
        # return redirect('cardgroups:group_details', pk)
    update_card_group_last(card_group)
    # cards = get_list_or_404(Card, card_group_id=pk, card_group__user=request.user)
    cards = list(cards)
    random.shuffle(cards)
    set_session_study_type(request, study_type)
    set_session_data(request, cards)
    index = index_of_selected_card(request)
    set_session_card(request, index)
    set_session_expire_date(request, expire_date)
    set_session_statistics(request)
    update_prority_level(request, index)

    template_name = 'cardgroups/show_card_in_study_screen.html'
    html = get_html(
        request,
        template_name,
        {
            'card': request.session.get('card'),
            'cardgroup_pk': pk
        }
    )
    context = {
        'card': request.session.get('card'),
        'cardgroup': card_group,
        'expiredate': expire_date,
        'html': html
    }

    return render(request, 'cardgroups/study.html', context)



def get_html(request, template_name, context):
    template = loader.get_template(template_name)
    return template.render(context, request)


def set_session_data(request, cards):
    max_priority_level = len(cards)
    data = list()
    for card in cards:
        data.append({'priority_level': max_priority_level, 'card':model_to_dict(card)})
        max_priority_level -= 1

    request.session['data'] = data


def set_session_study_type(request, study_type):
    request.session['study_type'] = study_type


def set_session_card(request, index):
    data = request.session.get('data')
    card = data[index]['card'].copy()
    study_type = request.session.get('study_type')
    if study_type == 'front':
        face_to_answer = 'back'
    else:
        face_to_answer = random.choice(['front', 'back'])
    card.pop(face_to_answer)
    start_time = timezone.now()

    request.session['card'] = {'index': index, 'card': card, 'start_time': str(start_time)}


def set_session_expire_date(request, expire_date):
    if isinstance(expire_date, datetime):
        request.session['expire_date'] = str(expire_date)
    else:
        request.session['expire_date'] = expire_date


def set_session_statistics(request, result=None):

    if result is not None:
        try:
            answered_correctly = request.session['statistics']['answered_correctly']
            answered_wrong = request.session['statistics']['answered_wrong']
        except KeyError:
            answered_correctly = 0
            answered_wrong = 0
            
        if result:
            answered_correctly += 1
        else:
            answered_wrong += 1
    else:
        answered_correctly = 0
        answered_wrong = 0

    statistics = {
        'answered_correctly': answered_correctly,
        'answered_wrong': answered_wrong
    }

    request.session['statistics'] = statistics


def update_card_group_last(card_group):
    card_group.last_study_at = timezone.now()
    card_group.study_count = F('study_count') + 1
    card_group.save()


def check_session(request, pk):
    if (request.session.get('data') and
        request.session.get('expire_date') and
        request.session.get('card') and
        request.session.get('statistics') and
        request.session.get('card')['card']['card_group'] == pk):
        expire_date = parser.parse(request.session.get('expire_date'))
        if expire_date > timezone.now():
            return True
    return False


def set_study_type(request, pk):
    try:
        study_type = request.POST['study_type']
    except KeyError:
        study_type = 'shuffle'
    
    if study_type not in ['shuffle', 'front']:
        messages.error(request, 'Ôn tập thất bại. Không có kiểu ôn tập là:' + str(study_type))
        return redirect(reverse('cardgroups:group_details', args=[pk])) 

    return study_type


def set_expire_date(request, card_group):
    try:
        duration = int(request.POST['new_study_duration'])
    except KeyError:
        duration = card_group.study_duration
    except ValueError:
        messages.error(request, 'Thời gian ôn tập phải là số nguyên dương')
        return None

    if isinstance(duration, timedelta):
        return timezone.now() + duration
    return timezone.now() + timedelta(minutes=duration)


def update_prority_level(request, index, speed=None, result=None):
    data = request.session.get('data')
    if speed is None and result is None:
        data[index]['priority_level'] = data[index]['priority_level'] - len(data)
        for item in data:
            item['priority_level'] += 1
    else:
        if not result:
            if len(data) > 3:
                data[index]['priority_level'] += len(data) - 3
            else:
                data[index]['priority_level'] += 2
        else:
            if speed == 'normal':
                data[index]['priority_level'] += round(len(data) * 20 / 100)
            elif speed == 'slow':
                data[index]['priority_level'] += round(len(data) * 40 / 100)

    request.session['data'] = data


def index_of_selected_card(request):
    data = request.session.get('data')
    max_priority_level = max(data, key=lambda x: x['priority_level'])['priority_level']
    index_cards = [i for i in range(len(data)) if data[i]['priority_level'] == max_priority_level]
    if len(index_cards) > 1:
        index_card = random.choice(index_cards)
    else:
        index_card = index_cards[0]

    return index_card



@login_required()
def ContinueStudyingView(request, pk):
    if request.is_ajax():
        if check_session(request, pk):
            index = index_of_selected_card(request)
            set_session_card(request, index)
            update_prority_level(request, index)
            template_name = 'cardgroups/show_card_in_study_screen.html'
            html = get_html(request, template_name, {'card': request.session.get('card'), 'cardgroup_pk': pk})

CardGroups/templates/cardgroups/create_group.html
{% extends "public/base.html" %}

{% load static %}

{% block head %}
    <title>Tạo chồng mới</title>
{% endblock%}

{% block header %}
    {% include "public/header_logout.html" %}
{% endblock %}

{% block content %}
<div class="mg-top-100">
    <div class="text-center mb-3">
        <span class="h3 fw-bold">Chồng mới</span>
    </div>
    <div class="row my-3">
        <div class="col-sm-12 col-md-3">
        </div>
        <div class="col-sm-12 col-md-6">
            <form action="" method="post" class="col-sm-12 col-md-10 mx-auto px-3">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_name">Tên chồng:</label>
                    {{ form.name }}
                    {% if form.name.errors %}
                        {{ form.name.errors }}
                    {% endif %}
                </div>
                {{ form.user }}
    
                <div class="mb-3">
                    <label for="id_study_duration">Thời gian ôn tập (phút):</label>
                    {{ form.study_duration }}
                    {% if form.study_duration.errors %}
                        {{ form.study_duration.errors }}
                    {% endif %}
                </div>
                <div class="text-center">
                    <button type="submit" class="btn bg-primary w-25 text-white">Lưu</button>
                    {% if form.non_field_errors %}
                        {{ form.non_field_errors }}
                    {% endif %}
                </div>
            </form>
        </div>
        <div class="col-sm-12 col-md-3">
        </div>
    </div>
</div>
{% endblock%}

CardGroups/templates/cardgroups/dashboard.html
{% extends "public/base.html" %}

{% load static %}

{% block head %}
<title>Flashcard</title>
{% endblock%}

{% block header %}
{% include "public/header_logout.html" %}
{% endblock %}

{% block content %}
<div class="mg-top-100">
    <div class="position-fixed btn-create-group end-0 z-index-1">

    <!-- <div class="position-fixed btn-create-group z-index-1"> -->
        <a href="{% url 'cardgroups:create_group' %}" class="py-3 ps-3 pe-2 create-group fw-bold"><i
                class="fas fa-plus"></i> Tạo Chồng</a>
    </div>
    <div class="container">
        <div class="col-md-5 text-center mb-3 mx-auto">
            <div class="h3 fw-bold mb-3">DASHBOARD</div>
                <form method="get">
                    <div class="mb-3 input-group">
                        <input type="search" name="group" class="form-control w-search">
                        <button type="submit" class="btn btn-primary px-4"><i class="fas fa-search"></i></button>
                    </div>
                </form>
                <div class="">
                    <a href="{% url 'cardgroups:create_group' %}" class="btn btn-primary fw-bold"><i
                        class="fas fa-plus"></i> Tạo Chồng</a>
                </div>
               
                
            </div>
        </div>

        {% if not cardgroup_list %}
        <div class="text-center">
            <span>Bạn hiện không có chồng card nào.</span>
        </div>
        {% else %}
        <div class="row row-cols-1 row-cols-md-2 mg-x-150">
            {% for cardgroup in cardgroup_list %}
            <div class="col mb-4">
                <div class="card card-group">
                    <div class="card-body">
                        <table class="table border-dark">
                            <thead>
                                <tr>
                                    <th colspan="2">
                                        <span class="card-title">{{ cardgroup.name }}</span>
                                        <button type="button" data-bs-toggle="modal"
                                            data-bs-target="#delete_group_{{ cardgroup.pk }}" title="Xóa"
                                            class="btn-close float-end"></button>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>Số card:</td>
                                    <td class="text-end">{{ cardgroup.card_count }}</td>
                                </tr>
                                <tr>
                                    <td>Số lần học:</td>
                                    <td class="text-end">{{ cardgroup.study_count }}</td>
                                </tr>
                                <tr>
                                    <td>Lần học gần nhất:</td>
                                    <td class="text-end">{{ cardgroup.last_study_at|date:'d-m-Y H:i' }}</td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="text-center">
                            <a href="{{ cardgroup.get_absolute_url }}" class="btn btn-primary col-sm-4">Chi tiết</a>
                            <a href="{% url 'cardgroups:study_group' cardgroup.pk %}" class="btn btn-success col-sm-4">Ôn bài</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" data-bs-backdrop="static" id="delete_group_{{ cardgroup.pk }}">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Thông báo</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <span>Bạn chắc chắn muốn xóa chồng này?</span>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                            <form action="{% url 'cardgroups:delete_group' cardgroup.pk %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Yes</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

<script src="{% static 'cardgroups/js/card_group.js' %}"></script>
{% endblock%}

CardGroups/templates/cardgroups/show_card_in_study_screen.html
{% load static %}

<div class="row text-center">
    <div class="col-sm-12 col-md-3">
    </div>
    <div class="col-sm-12 col-md-6">
        {% if card.card.front %}
        <div class="mb-3">
            <label class="mb-2"> Mặt trước</label>
            <br>
            <textarea name="" id="id_front" cols="50" disabled rows="5"
                class="w-100 text-black bg-white">{{ card.card.front }}</textarea>
        </div>
        <div class="mb-3">
            <form id="form-check-result" method="post">
                {% csrf_token %}
                <label for="id_back" class="mb-2">Mặt sau</label>
                <br>
                <textarea name="back" data-bs-toggle="popover" data-bs-trigger="focus"
                    data-bs-content="Ctrl + Enter để kiểm tra kết quả" id="id_back" autofocus cols="50" rows="5"
                    class="w-100 txt_keyboard_events"></textarea>
            </form>
        </div>
        {% else %}
        <div class="mb-3">
            <label class="mb-2"> Mặt sau</label>
            <br>
            <textarea name="" id="id_back" cols="50" disabled rows="5"
                class="w-100 text-black bg-white">{{ card.card.back }}</textarea>
        </div>
        <div class="mb-3">
            <form id="form-check-result" method="post">
                {% csrf_token %}
                <label for="id_front" class="mb-2">Mặt trước</label>
                <br>
                <textarea name="front" data-bs-toggle="popover" data-bs-trigger="focus"
                    data-bs-content="Ctrl + Enter để kiểm tra kết quả" id="id_front" autofocus cols="50" rows="5"
                    class="w-100 txt_keyboard_events"></textarea>
            </form>
        </div>
        {% endif %}
    </div>
    <div class="col-sm-12 col-md-3">
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-3"></div>
    <div class="col-sm-12 col-md-6">
        <div class="row">
            <div class="col-sm-12 col-md-9">
                <div id="show-result">
                    <span class="fw-bold">Nhấn kiểm tra để xem kết quả</span>
                </div>
            </div>
            <div class="col-sm-12 col-md-3">
                <div class="text-center">
                    <div id="btn" class="mb-2">
                        <button id="check-result" type="button" class="btn btn-primary">Kiểm tra</button>
                    </div>
                    <button id="end-study" data-bs-toggle="modal" data-bs-target="#modal-end-study" type="button" class="btn btn-danger">Kết thúc</button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-3"></div>
</div>
<div class="modal fade" data-bs-backdrop="static" id="modal-end-study">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Thông báo</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span>Bạn chắc chắn muốn kết thúc quá trình ôn bài này?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Trở lại</button>
                <button id="confirm-end-study" type="button" class="btn btn-danger">Kết thúc</button>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'cardgroups/js/study.js' %}"></script>

CardGroups/templates/cardgroups/show_result_in_study_screen.html
{% load static %}

<div class="row text-center">
    <div class="col-sm-12 col-md-3">
    </div>
    <div class="col-sm-12 col-md-6">
        {% if card.card.front %}
        <div class="mb-3">
            <label class="mb-2"> Mặt trước</label>
            <br>
            <textarea name="" id="id_front" cols="50" disabled rows="5"
                class="w-100 text-black bg-white">{{ card.card.front }}</textarea>
        </div>
        <div class="">
            <label for="id_back" class="mb-2">Mặt sau</label>
            <br>
            <textarea name="" id="id_front" cols="50" rows="5" data-bs-trigger="focus" data-bs-toggle="popover"
                data-bs-content="Ctrl + Enter để tiếp tục"
                class="w-100 text-black bg-white txt_keyboard_events">{{ answered }}</textarea>
            </div>
            {% else %}
            <div class="mb-3">
                <label class="mb-2"> Mặt sau</label>
                <br>
                <textarea cols="50" disabled rows="5" class="w-100 text-black bg-white">{{ card.card.back }}</textarea>
            </div>
            <div class="mb-3">
                <label for="id_back" class="mb-2">Mặt trước</label>
                <br>
                <textarea cols="50" rows="5" data-bs-trigger="focus" data-bs-toggle="popover"
                    data-bs-content="Ctrl + Enter để tiếp tục"
                    class="w-100 text-black bg-white txt_keyboard_events">{{ answered }}</textarea>
            </div>
        {% endif %}
    </div>
    <div class="col-sm-12 col-md-3">
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-3">

    </div>
    <div class="col-sm-12 col-md-6">
        <div class="row">
            <div class="col-sm-9">
                <div id="show-result">
                    {% if result is True %}
                    <span class="fw-bold fw-bold text-success h5">Tuyệt vời. Bạn ghi nhớ rất tốt</span>
                    {% else %}
                    <span class="fw-bold fw-bold h5 text-danger">Kết quả chưa chính xác</span>
                    {% endif %}
                    <br>
                    <span class="fw-bold"><small class='fw-bold h6'>Đáp án: </small>{{ correct_answer }}</span>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="text-center">
                    <div id="btn" class="mb-2">
                        <button id="next-card" type="button" class="btn btn-primary">Tiếp tục</button>
                    </div>
                    <button id="end-study" data-bs-toggle="modal" data-bs-target="#modal-end-study" type="button"
                        class="btn btn-danger">Kết thúc</button>

                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-3"></div>
</div>
<div class="modal fade" data-bs-backdrop="static" id="modal-end-study">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Thông báo</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <span>Bạn chắc chắn muốn kết thúc quá trình ôn bài này?</span>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Trở lại</button>
                <button id="confirm-end-study" type="button" class="btn btn-danger">Kết thúc</button>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'cardgroups/js/study.js' %}"></script>

CardGroups/templates/cardgroups/show_statistics_in_study_screen.html
{% load static %}
{% load mathfilters %}
<div class="row">
    <div class="col-12 col-md-3">
    </div>
    <div class="col-12 col-md-6">
        <div class="card">
            <div class="card-header h5 text-center fw-bold">
                Thống kê kết quả vừa ôn tập
            </div>
            <div class="card-body">
                <table class="table">
                    <tbody>
                        <tr>
                            <th>Số lần trả lời đúng</th>
                            <td>{{ answered_correctly }}</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th>Số lần trả lời sai</th>
                            <td>{{ answered_wrong }}</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <th>Tổng số lần trả lời</th>
                            <th>{{ answered_correctly|add:answered_wrong }}</th>
                        </tr>
                    </tbody>
                </table>

                <div class="text-center">
                    <a href="{% url 'cardgroups:learn' %}" class="btn btn-primary w-25">OK</a>
                </div>
            </div>
        </div>

    </div>
    <div class="col-12 col-md-3">
    </div>
</div>
{% if messages %}
{% for message in messages %}
<div class="position-fixed bottom-0 end-0 p-3 messages" style="z-index: 10001">
    <div id="liveToast" class="toast hide" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header" style="background: #004aad;">
            <img src="{% static 'public/images/flash_card.png' %}" class="rounded me-2" width="100px" alt="">
            <strong class="me-auto text-white fw-normal"></strong>
            <small class="text-white">Vừa xong</small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body">
            {{ message }}
        </div>
    </div>
</div>
{% endfor %}
{% endif %}
<script src="{% static 'public/js/base.js' %}"></script>

CardGroups/templates/cardgroups/study.html
{% extends "public/base.html" %}

{% load static %}

{% block head %}
<title>Luyện tập</title>
{% endblock%}

{% block header %}
{% include "public/header_logout.html" %}
{% endblock %}

{% block content %}
<div class="mg-top-100">
    <div class="text-center mb-3">
        <span class="h3 fw-bold">Chồng card: {{ cardgroup.name }}</span>
        <br>
        <span>Ôn tập đến: {{ expiredate|date:'d-m-Y H:i:s' }}</span>
    </div>

    <div id="card_content" class="container">
        {{ html }}
    </div>
    <span class="d-hidden" id="end-study-url" data-url="{% url 'cardgroups:end_study' cardgroup.pk %}"></span>
    <span class="d-hidden" id="check-card-url" data-url="{% url 'cardgroups:check_result' cardgroup.pk %}"></span>
    <span class="d-hidden" id="next-card-url" data-url="{% url 'cardgroups:continues_studying' cardgroup.pk %}"></span>
</div>
{% endblock%}