FlashCard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from CardGroups import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.url')),
    path('', include('CardGroups.url')),
    path('cards/', include('Cards.url')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Cards/models.py
from CardGroups.models import CardGroup
from django.db import models


class Card(models.Model):
    card_group = models.ForeignKey(CardGroup, on_delete=models.CASCADE, related_name='cards')
    front = models.TextField()
    back = models.TextField()

    def __str__(self):
        return self.front


    class Meta:
        db_table = "card"
        ordering = ["-id"]

Cards/forms.py
from django import forms
from Cards.models import Card


class CardForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['card_group'].disabled = True
        

    class Meta:
        model = Card
        fields = '__all__'
        widgets = {
            'front': forms.Textarea(attrs={
                'class': 'form-control input_card',
                'rows':'5',
                'data-bs-trigger': 'focus',
                'data-bs-toggle': 'popover',
                'data-bs-content': '''- Ctrl + Enter nếu card này là card cuối cùng.
                                    <br />
                                    - AltKey + Enter nếu bạn muốn thêm nhiều card khác.''',
                'data-bs-html': 'true'
            
            }),
            'back': forms.Textarea(attrs={
                'class': 'form-control input_card',
                'rows':'5',
                'data-bs-trigger': 'focus',
                'data-bs-toggle': 'popover',
                'data-bs-content': '''- Ctrl + Enter nếu card này là card cuối cùng.
                                    <br />
                                    - AltKey + Enter nếu bạn muốn thêm nhiều card khác.''',
                'data-bs-html': 'true'
            }),
            'card_group': forms.TextInput(attrs={'hidden': 'True;'})
        }

Cards/views.py
from django.views import generic
from django.shortcuts import get_object_or_404, redirect, render
from Cards.models import Card
from Cards.forms import CardForm
from CardGroups.models import CardGroup
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Count
from django.contrib import messages



@method_decorator(login_required, name='dispatch')
class CreateCard(generic.CreateView):
    model = Card
    form_class = CardForm
    template_name = 'cards/create_card.html'

    def get_initial(self):
        init = super().get_initial()
        init['card_group'] = self.kwargs.get('pk')
        return init

    def get(self, request, *args: str, **kwargs):
        if kwargs['btn'] == 'begin':
            return super().get(request, *args, **kwargs)
        else:
            return redirect('cards:create_card', self.kwargs['pk'], 'begin')

    def get_success_url(self):
        messages.success(self.request, 'Chúc mừng. Bạn đã tạo card thành công')
        if self.kwargs['btn'] == 'continue':
            return reverse('cards:create_card', args=[self.kwargs['pk'], 'begin'])
        else:
            return reverse('cardgroups:group_details', args=[self.kwargs['pk']])


    def get_context_data(self, **kwargs):
        groups = CardGroup.objects.prefetch_related('cards').annotate(
                card_count=Count('cards__id'))
        group = get_object_or_404(groups, id=self.kwargs['pk'], user_id=self.request.user.pk)
       
        kwargs['group'] = group
        return super().get_context_data(**kwargs)




@login_required()
def DeleteCard(request, id_group, id_card):
    instance = get_object_or_404(Card, pk=id_card, card_group_id=id_group, card_group__user=request.user)
    if request.method == 'POST':
        instance.delete()
    return redirect('cardgroups:group_details', id_group)



@login_required()
def UpdateCard(request, id_group, id_card, page, limit):
    instance = get_object_or_404(Card, pk=id_card, card_group_id=id_group, card_group__user=request.user)
    if request.method == 'POST':
        form = CardForm(instance=instance, data={**request.POST.dict(), 'card_group': id_group})
        if form.is_valid():
            form.save()
        else:
            messages.error(request, 'Cập nhật card thất bại')

    return redirect(reverse('cardgroups:group_details', args=[id_group]) + '?page=' + str(page) + '&limit=' + str(limit))

Cards/templates/cards/create_card.html
{% extends "public/base.html" %}

{% load static %}

{% block head %}
<title>Tạo chồng mới</title>
{% endblock%}

{% block header %}
{% include "public/header_logout.html" %}
{% endblock %}

{% block content %}
<div class="mg-top-100">
    <div class="text-center mb-3">
        <span class="h3 fw-bold">Card mới</span>
    </div>
    <form method="post" class="col-sm-12 col-md-7 mx-auto px-4">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_card_group">Chồng:</label>
            <span class="fw-bold h4">{{ group.name }}</span>
            <span class="float-end">Số card: {{ group.card_count }}</span>
            {{ form.card_group }}
            {% if form.card_group.errors %}
            {{ form.card_group.errors }}
            {% endif %}
        </div>

        <!-- <input type="hidden" id="id_card_group" name="card_group" value="{{ group.pk }}">  -->
        <div class="mb-3">
            <label for="id_front">Mặt trước:</label>
            {{ form.front }}
            {% if form.front.errors %}
            {{ form.front.errors }}
            {% endif %}
        </div>
        <div class="mb-3">
            <label for="id_front">Mặt sau:</label>
            {{ form.back }}
            {% if form.back.errors %}
            {{ form.back.errors }}
            {% endif %}
        </div>
        <div class="text-center">
            <button id="btn_continue" formaction="{% url 'cards:create_card' pk=group.pk btn='continue' %}" type="submit"
                class="btn bg-primary btn-width text-white">Thêm card</button>
            <button id="btn_done" formaction="{% url 'cards:create_card' pk=group.pk btn='done' %}" type="submit"
                class="btn bg-success btn-width text-white display-none">Xong</button>
            <a id="link_done" href="{% url 'cardgroups:learn' %}" class="btn bg-success btn-width text-white">Xong</a>
            <div>
                {% if form.non_field_errors %}
                {{ form.non_field_errors }}
                {% endif %}
            </div>
        </div>
    </form>
    
</div>
<script src="{% static 'cards/js/create_card.js' %}"></script>
{% endblock%}