FlashCard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from CardGroups import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.url')),
    path('', include('CardGroups.url')),
    path('cards/', include('Cards.url')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
import uuid
from django.contrib.auth.models import AbstractBaseUser, UserManager



class User(AbstractBaseUser):
    USERNAME_FIELD = "username"
    objects = UserManager()

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username = models.CharField(max_length=150, null=True, unique=True)
    email = models.EmailField(max_length=100, unique=True, null=True)
    is_superuser = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    avatar = models.ImageField(null=True, upload_to='images/', blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username


    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    class Meta:
        db_table = "user"

users/forms.py
from django import forms
from django.forms.widgets import PasswordInput
from users.models import User
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import  password_validation



class UserForm(forms.ModelForm):
    password = forms.CharField(
        min_length=6,
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'},
        ),
    )
    email = forms.EmailField(
        error_messages={'unique':"Email  đã được đăng kí."},
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = User
        exclude = ['is_superuser', 'last_login', 'is_staff', 'is_active']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'avatar': forms.FileInput(attrs={
                'class': 'form-control form-control-sm'
            })
        }
        error_messages = {
            'username': {
                'unique':"Username đã được đăng kí."
            }
        }



    def save(self, commit=True):
        self.instance.set_password(self.cleaned_data['password'])
        user = super().save(commit=commit)
        return user


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=150,
        required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    password = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control'}))


class PasswordChangeForm(forms.Form):
    def __init__(self, user=None, instance=None, *args, **kwargs):
        self.instance = instance
        self.user = user
        super().__init__(*args, **kwargs)

    current_password = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=PasswordInput(attrs={'class': 'form-control'}))
    
    def clean_password(self):
        password = self.cleaned_data['password']
        password_validation.validate_password(password, self.user)
        return password



class ProfileForm(forms.ModelForm):
    email = forms.EmailField(
        error_messages={'unique':"Email  đã được đăng kí."},
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = User
        exclude = ['is_superuser', 'last_login', 'is_staff', 'password', 'is_active']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'avatar': forms.FileInput(attrs={
                'class': 'form-control form-control-sm'
            })
        }
        error_messages = {
            'username': {
                'unique':"Username đã được đăng kí."
            }
        }


class SetPasswordFormCustom(forms.Form):
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    new_password = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class': 'form-control'
        }),
    )

    def clean_new_password(self):
        new_password = self.cleaned_data['new_password']
        password_validation.validate_password(new_password, self.user)
        return new_password


    def save(self, commit=True):
        password = self.cleaned_data["new_password"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user

users/views.py
import re
from django.shortcuts import redirect, render
from django.views import generic, View
from users.forms import UserForm, LoginForm, PasswordChangeForm, ProfileForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.core.validators import validate_email


def LoginView(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        try:
            validate_email(request.POST['username'])
        except ValidationError:
            username = request.POST['username']
        else:
            try:
                username = get_user_model().objects.get(email=request.POST['username']).username
                form = LoginForm({'username':username, 'password': request.POST['password']})
            except get_user_model().DoesNotExist:
                form.add_error('__all__', 'Tài khoản hoặc mật khẩu không chính xác!')

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Đăng nhập thành công.')
                return redirect('cardgroups:learn')
            else:
                messages.error(request, 'Đăng nhập thất bại.')
                form.add_error('__all__', 'Tài khoản hoặc mật khẩu không chính xác!')
    else:
        form = LoginForm()

    return LoginRegisterForm(request=request, login_form=form)




def LogoutView(request):
    logout(request)
    return redirect('users:login')



def AddUser(request):
    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Đăng kí tài khoản thành công.')
            return redirect('cardgroups:learn')
        else:
            messages.error(request, 'Đăng kí tài khoản thất bại.')
    else:
        form = UserForm()
    return LoginRegisterForm(request, register_form=form)


def LoginRegisterForm(request, register_form = UserForm(), login_form = LoginForm()):
    return render(request,'users/login_register.html', {
            'register_form': register_form,
            'login_form': login_form
        }
    )




@login_required()
def ProfileView(request):
    if request.method == 'POST':
        user_form = ProfileForm(instance=request.user, data=request.POST, files=request.FILES)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'Cập nhật thông tin cá nhân thành công.')
            return redirect('users:profile')
        else:
            messages.error(request, 'Cập nhật thông tin cá nhân thất bại.')

    else:
        user_form = ProfileForm(instance=request.user)
    return render(request,'users/profile.html',{'form': user_form})


@login_required()
def PasswordChange(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            user = request.user
            if user.check_password(form.cleaned_data['current_password']):
                user.set_password(form.cleaned_data['password'])
                user.save()
                update_session_auth_hash(request, user)
                messages.success(request, 'Thay đổi mật khẩu thành công.')
                return redirect('cardgroups:learn')
            else:
                messages.error(request, 'Thay đổi mật khẩu thất bại.')
                form.add_error('current_password', 'Mật khẩu không đúng')
    else:
        form = PasswordChangeForm()
    return render(request, 'users/password_change.html', {'form': form})



# class AddUser(View):
#     # model = User
#     # fields = '__all__'
#     # # form_class = UserForm
#     template_name = 'users/add_user.html'
#     # # success_url = reverse_lazy('users:login')

#     # def get_context_data(self, **kwargs):
#     #     context = super().get_context_data(**kwargs)
#     #     return context

#     def get(self, request, *args, **kwargs):
#         form = UserForm()
#         return render(request, self.template_name, {'form': form})

users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'users/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/v4-shims.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    {% block head %}

    {% endblock %}
</head>
<body>
    <div class="header" >
        <div class="modal fade" data-bs-backdrop="static" id="LogoutModal">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Đăng xuất</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <span>Bạn chắc chắn muốn đăng xuất?</span>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                        <form action="{% url 'users:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Yes</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% block header %}

        {% endblock %}
    </div>
    {% block content %}

    {% endblock %}
    <script src="{% static 'users/js/login_logout.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/header_login.html
{% load static %}

<div class="d-flex justify-content-between mb-3" style="background: #004aad;">
    <div class="my-auto">
        <img src="{% static 'users/images/Flashcard.png' %}" alt="" width="230px">
    </div>
    <div class="p-3">
        <a type="button" class="btn btn-light" style="background: #0c0c8a; color: white; border: 0px;" href="{% url 'users:login' %}">
            <div class="clearfix">
                <div class="float-start me-1">
                    <i class="fas fa-sign-in-alt fs-5"></i>
                </div>
                <div class="float-end">
                    <span>Đăng nhập</span>
                </div>
            </div>
        </a>
    </div>
</div>

users/templates/users/login_register.html
{% extends "public/base.html" %}
{% load static %}

{% block head %}
    <title>Login</title>
{% endblock %}

{% block header %}
{% include "public/header_login.html" %}
{% endblock %}


{% block content %}
    <div class="modal fade modal-dialog modal-dialog-centered" id='LoginModal' data-bs-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Đăng nhập</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>

                <div class="modal-body mx-auto">
                    <form action="{% url 'users:login' %}" method="post">
                        {% csrf_token %}

                        <div class="mb-3">
                            <label for="id_username" class="form-label">Username or Email</label>
                            <div class="col-sm-12">
                                {{ login_form.username}}
                                {% if login_form.username.errors %}
                                    {{ login_form.username.errors }}
                                {% endif %}
                                {% if login_form.email.errors %}
                                    {{ login_form.email.errors }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="" class="form-label">Password</label>
                            <div class="col-sm-12">
                                {{ login_form.password}}
                                {% if login_form.password.errors %}
                                    {{ login_form.password.errors }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="mb-3 text-center">
                            <input class="btn btn-primary col-sm-5" type="submit" value="Đăng nhập">
                        </div>
                        {% if login_form.non_field_errors %}
                            {{ login_form.non_field_errors }}
                        {% endif %}
                    </form>
                </div>
                <div class="modal-footer d-flex justify-content-between mb-3">
                        <div class="p-2">
                            <a href="{% url 'users:password_reset' %}">Quên mật khẩu</a>
                        </div>
                        <button type="button" class="btn btn-success p-2" data-bs-toggle="modal" data-bs-target="#RegisterModal">Đăng ký</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="RegisterModal" data-bs-backdrop="static">
        <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Đăng ký</h4>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>

                <div class="modal-body">
                    <form action="{% url 'users:register' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="clearfix row">
                            <div class="col-sm-12 col-md-6 mb-3">
                                <div class="px-4">
                                    <div class="text-center">
                                        <img id="image" class="bg-white mb-3"
                                            src="{% static 'public/images/avatar.jpg' %}" width='150px'
                                            height="150px" />
                                        <div class="">
                                            <label for="" class="form-label mb-1">Avatar</label>
                                            <div class="col-sm-12 col-md-10 mx-auto">
                                                {{ register_form.avatar }}
                                                {% if register_form.avatar.errors %}
                                                    {{ register_form.avatar.errors }}
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-12 col-md-6">
                                <div class="px-4">
                                    <div class="mb-3">
                                        <label for="" class="form-label">Username</label>
                                        <div class="col-sm-12 col-md-sm-12">
                                            {{ register_form.username}}
                                            {% if register_form.username.errors %}
                                                {{ register_form.username.errors }}
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="mb-3">
                                        <label for="" class="form-label">Email</label>
                                        <div class="col-sm-12 col-md-12">
                                            {{ register_form.email }}
                                            {% if register_form.email.errors %}
                                                {{ register_form.email.errors }}
                                            {% endif %}
                                        </div>
                                    </div>
                                    <div class="mb-3">
                                        <label for="" class="form-label">Password</label>
                                        <div class="col-sm-12 col-md-sm-12">
                                            {{ register_form.password}}
                                            {% if register_form.password.errors %}
                                                {{ register_form.password.errors }}
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="mb-3 text-center">
                            <input class="btn btn-success w-25" type="submit" value="Đăng ký">
                            {% if register_form.non_field_errors %}
                                {{ register_form.non_field_errors }}
                            {% endif %}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#LoginModal">Đăng nhập</button>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'users/js/login_register.js' %}"></script>
{% endblock %}

users/templates/users/password_change.html
{% extends "public/base.html" %}

{% load static %}

{% block head %}
<title>Flash Card</title>
{% endblock%}

{% block header %}
{% include "public/header_logout.html" %}
{% endblock %}

{% block content %}
<div class="mg-top-100">
    <div class="row px-4">
        <form method="POST" class="col-sm-12 col-md-4 mx-auto text-center">
            {% csrf_token %}
            <span class="h3 fw-bold">Thay đổi mật khẩu</span>
            <div class="mt-4 text-start">
                <label for="id_current_password" class="form-label">Mật khẩu hiện tại:</label>
                {{ form.current_password }}
                {% if form.current_password.errors %}
                {{ form.current_password.errors }}
                {% endif %}
            </div>
            <div class="mt-4 text-start mb-3">
                <label for="id__password" class="form-label">Mật khẩu mới:</label>
                {{ form.password }}
                {% if form.password.errors %}
                {{ form.password.errors }}
                {% endif %}
            </div>
            <button class="btn btn-primary w-25" type="submit">Lưu</button>
            {% if form.non_field_errors %}
            {{ form.non_field_errors }}
            {% endif %}
        </form>
    </div>
</div>

<script src="{% static 'users/js/pass_change.js' %}"></script>

{% endblock%}

users/templates/users/password_reset_complete.html
{% extends 'public/base.html' %}

{% load static %}

{% block head %}
<title>Quên mật khẩu</title>
{% endblock %}

{% block header %}
{% include "public/header_login.html" %}
{% endblock %}

{% block content %}
<div class="col-sm-12 col-md-4 mx-auto px-4">
    <span>Bạn đã thay đổi mật khẩu thành công.</span>
    <br>
    <br>
    <span>Trở lại trang <a href="{% url 'users:login' %}">đăng nhập</a></span>
</div>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'public/base.html' %}

{% load static %}

{% block head %}
<title>Quên mật khẩu</title>
{% endblock %}

{% block header %}
{% include "public/header_login.html" %}
{% endblock %}

{% block content %}
<div class="row">
    <form method="POST" class="col-sm-12 col-md-4 mx-auto px-4">
        {% csrf_token %}
        <div class="text-center">
            <span class="h3 fw-bold">Đặt lại mật khẩu</span>
            <div class="mt-4 mb-3 text-start">
                <!-- <label for="id_new_password" class="form-label">Mật khẩu mới:</label> -->
                {{ form.new_password.label_tag }}
                {{ form.new_password }}
                {% if form.new_password.errors %}
                {{ form.new_password.errors }}
                {% endif %}
            </div>
            <button class="btn btn-primary w-25" type="submit">Gửi</button>
            {% if form.non_field_errors %}
            {{ form.non_field_errors }}
            {% endif %}
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'public/base.html' %}

{% load static %}

{% block head %}
    <title>Quên mật khẩu</title>
{% endblock %}

{% block header %}
    {% include "public/header_login.html" %}
{% endblock %}

{% block content %}
<div class="px-4">
        <span>Chúng tôi đã gửi thông tin vào email của bạn.</span>
        <br>
        <span>Vui lòng kiểm tra email và làm theo hướng dẫn để đặt lại mật khẩu.</span>
        <br>
        <br>
        <span>Trở lại trang <a href="{% url 'users:login' %}">đăng nhập</a></span>
</div>

{% endblock %}

users/templates/users/password_reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Đặt lại mật khẩu</title>
</head>
<body>
    <span>Ai đó đã yêu cầu đặt lại mật khẩu cho {{ email }} này.</span>
<br>
<span>
Nếu là bạn hãy vui lòng truy cập đường link dưới đây để đổi mật khẩu:
</span>
<a href="{{ protocol}}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
    link
</a>
</body>
</html>

users/templates/users/password_reset_form.html
{% extends 'public/base.html' %}

{% load static %}

{% block head %}
<title>Quên mật khẩu</title>
{% endblock %}

{% block header %}
{% include "public/header_login.html" %}
{% endblock %}

{% block content %}
<div class="row px-4">
    <form method="POST" class="col-sm-12 col-md-4 mx-auto text-center">
        {% csrf_token %}
        <span class="h3 fw-bold">Quên mật khẩu</span>
        <div class="mt-4 text-start mb-3">
            <label for="id_email my-2" class="form-label">Email của bạn:</label>
            <input type="email" class="form-control" name="email" autocomplete="email"
                maxlength="254" required id="id_email">
        </div>
        <button class="btn btn-primary w-25" type="submit">Gửi</button>
    </form>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends 'public/base.html' %}

{% load static %}

{% block head %}
<title>Hồ sơ</title>
{% endblock %}

{% block header %}
{% include "public/header_logout.html" %}
{% endblock %}

{% block content %}
<div class="mg-top-100">
    <div class="text-center">
        <span class="h3 fw-bold">Thông tin cá nhân</span>
    </div>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row my-3">
            <div class="col-sm-12 col-md-2">
            </div>
            <div class="col-sm-12 col-md-8 row">
               <div class="col-sm-12 col-md-6">
                    <div class="p-2 mx-3 text-center">
                        {% if form.instance.avatar %}
                        <img id='get_avatar' src="{{ form.instance.avatar.url }}" alt="" width='250px' height="250px">
                        {% else %}
                        <img id="get_avatar" class="bg-white mb-3"
                            src="{% static 'public/images/avatar.jpg' %}" width='250px'
                            height="250px" />
                        {% endif %}
                        <div class="mt-1">Ảnh đại diện</div>
                    </div>
               </div>
                <div class="col-sm-12 col-md-6">
                    <div class="p-2 mx-3">
                        <div>
                            <label for="id_username">Tên đăng nhập:</label>
                            {{ form.username }}
                            {% if form.username.errors %}
                            {{ form.username.errors }}
                            {% endif %}
                        </div>
                        <div class="mt-4">
                            <label for="id_email">Email:</label>
                            {{ form.email }}
                            {% if form.email.errors %}
                            {{ form.email.errors }}
                            {% endif %}
                        </div>
                        <div class="mt-4">
                            <label for="id_avatar">Ảnh đại diện</label>
                            {{ form.avatar }}
                            {% if form.avatar.errors %}
                            {{ form.avatar.errors }}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-2">
            </div>
        </div>
        <div class="text-center">
            {% if form.non_field_errors %}
            {{ form.non_field_errors }}
            {% endif %}
            <button class="btn btn-success w-25" type="submit">Lưu</button>
        </div>
    </form>
</div>
<script src="{% static 'users/js/profile.js' %}"></script>
{% endblock %}